FROM quay.io/pypa/manylinux_2_28_x86_64

ARG MANYLINUX_IMAGE
RUN : "${MANYLINUX_IMAGE?Missing arument: MANYLINUX_IMAGE needs to be set}"

RUN echo "$MANYLINUX_IMAGE" > /usr/local/bin/MANYLINUX_IMAGE
COPY manylinux_functions.sh /usr/local/bin/
COPY prepare_env.sh /usr/local/bin/
RUN /usr/local/bin/prepare_env.sh
